development:
  sessions:
    default:
      database: statistics
      hosts:
        - localhost:27017
production:
  sessions:
    default:
      database: statistics
      hosts:
        - localhost:27017
